force-app/main/default/objects/New_Student__c/New_Student__c.object-meta.xml
<CustomObject>
    <label>New Student</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>New Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>New Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/New_Student__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Student__c/fields/Graduated__c.field-meta.xml
<CustomField>
    <fullName>Graduated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Graduated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/New_Student__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Student__c/fields/Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Mobile_No__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/StudentController.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-05-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class StudentController {
  @AuraEnabled
  public static string createStudent(
    String firstName,
    String lastName,
    Date dob,
    Integer age,
    String gender,
    String mobileNo,
    Boolean graduated
  ) {
      New_Student__c student = new New_Student__c(
      First_Name__c = firstName,
      Last_Name__c = lastName,
      Date_of_Birth__c = dob,
      Age__c = age,
      Gender__c = gender,
      Mobile_No__c = mobileNo,
      Graduated__c = graduated
    );

    try {
      insert student;
      return 'SUCCESS';
    } catch (Exception e) {
      String exec = e.getMessage();
      return exec;
    }
  }
}