force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Shows all the errors</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Log_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Log_Date_Time__c</fullName>
    <description>Enter Date &amp; Time details when the Error Occurred</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Store the Date &amp; Time details when the Error Occurred</inlineHelpText>
    <label>Log Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <description>Enter the Complete Stack Track about the Problem</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Stores the Complete Stack Track about the Problem</inlineHelpText>
    <label>Log Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>The Name of Either Apex Class or Apex Trigger</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The Name of Either Apex Class or Apex Trigger</inlineHelpText>
    <label>Process Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExceptionHandling.cls
public class ExceptionHandling {
    public static void exceptionmethod(String logDetails, String processName)
    {
        Error_Log__c loger=new Error_Log__c();
        loger.Log_Date_Time__c=dateTime.now();
        loger.Log_Details__c=logDetails;
        loger.Process_Name__c=processName;
        try{
            insert loger;
        }
        catch(Exception e)
        {
            System.debug('Error'+e.getMessage());
        }
    }
}