force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Enter Email Address</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Provide Information about email address</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Enter Informations about Event</description>
    <label>Event</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>Enter End Date/Time</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter End Date/Time</inlineHelpText>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enter Event is live or not</description>
    <inlineHelpText>Gives Information about Event is live or not</inlineHelpText>
    <label>Live</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>Enter Maximum Seats in your Event</description>
    <inlineHelpText>Maximum Seats in Event</inlineHelpText>
    <label>Max Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Enter your name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter your name</inlineHelpText>
    <label>Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Enter Start Date-Time</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter Start Date-Time</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <description>Select Attendee</description>
    <inlineHelpText>Give Information about Attendee</inlineHelpText>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Select The Event</description>
    <inlineHelpText>Give Information about Event</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EventAttendeeTestUtility.cls
public class EventAttendeeTestUtility {
    public static List<Event_Attendee__c> createRecords(String name, Integer count, Boolean isInsert) {
        List<Event_Attendee__c> eventList = new List<Event_Attendee__c>();

        Event__c tempEvent = new Event__c(Name__c = 'Test Event', Start__c = Date.today(), End__c = Date.today().addDays(10), Max_Seats__c=50, Live__c = true);
        insert tempEvent;
        
        Attendee__c tempAttendee = new Attendee__c(Name = 'Aman Tyagi', Email__c = 'aman.tyagi@mirketa.com');
        insert tempAttendee;

        for (Integer i = 0; i < count; i++) {
            Event_Attendee__c temp = new Event_Attendee__c();
            temp.Name = name + ' ' + i;
            temp.Event__c = tempEvent.Id;
            temp.Attendee__c = tempAttendee.Id;
            eventList.add(temp);
        }

        if (isInsert) {
            insert eventList;
        }

        return eventList;
    }
}