force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Enter Email Address</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Provide Information about email address</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Enter Informations about Event</description>
    <label>Event</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Enter your location</description>
    <inlineHelpText>Provides Information about Location</inlineHelpText>
    <label>Location</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Enter your name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter your name</inlineHelpText>
    <label>Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Select your Event Organizer</description>
    <inlineHelpText>Select your Event Organizer</inlineHelpText>
    <label>Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Enter Start Date-Time</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter Start Date-Time</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <description>Select Attendee</description>
    <inlineHelpText>Give Information about Attendee</inlineHelpText>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Select The Event</description>
    <inlineHelpText>Give Information about Event</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <description>Enter the Informations about Event Organizer for event</description>
    <label>Event Organizer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location (Address Book)</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Street</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (Address Book)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AttendeeTriggerHandeller.cls
public class AttendeeTriggerHandeller {
    public static void sendEmail(List<Event_Attendee__c> newList){
        Set<Id> newEvtAtt = new Set<Id>();
        for(Event_Attendee__c evtAtt : newList){
            newEvtAtt.add(evtAtt.Id);
        }
        List<Event_Attendee__c> eventAttendeeList = [SELECT Id, Event__r.Name__c, Attendee__r.Name, Event__r.Location__r.Name, 
                                                    Event__r.Organizer__r.Name, Event__r.Start__c,Attendee__r.Email__c 
                                                    FROM Event_Attendee__c WHERE Id IN :newEvtAtt];     
        List<Messaging.Email> emailList = new List<Messaging.Email>();
        for (Event_Attendee__c eventAttendee : eventAttendeeList) 
        {  try{
            if (eventAttendee.Attendee__r.Email__c != null) {
                  Messaging.SingleEmailMessage emailMsg = new Messaging.SingleEmailMessage();
                  String[] toAddress = new String[] { eventAttendee.Attendee__r.Email__c }; 
                  emailMsg.setToAddresses(toAddress);
                  String emailSub = 'Pass for the ' + eventAttendee.Event__r.Name + ' event';
                  emailMsg.setSubject(emailSub);
                  String content = 'Dear ' +  eventAttendee.Attendee__r.Name + ',<br/>' +
				                   'Thank you for registering for '+ eventAttendee.Event__r.Name 
                                   +' which will be Organized on '+ eventAttendee.Event__r.Start__c + 
                                   ' & will be held in ' + eventAttendee.Event__r.Location__r.Name +
				                   ' We are excited to have you, see you at the event. ' + '<br/>'+
				                   ' Thanks, '+ '<br/>' +
				                   eventAttendee.Event__r.Organizer__r.Name + '<br/>' +
                                   'Event Organizer';
                 emailMsg.setHtmlBody(content);
                 emailList.add(emailMsg);
 
            }
       Messaging.sendEmail(emailList);
        }
         catch(Exception e){
             ExceptionHandling.exceptionMethod(e.getMessage(), 'EventAttendeeEmailHandler');
         }
        }
    }
   }