force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Enter Informations about Event</description>
    <label>Event</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <description>Enter Details of Event Speaker</description>
    <label>Event-Speaker</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Select Event</description>
    <inlineHelpText>Information of Event</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>Select Speaker</description>
    <inlineHelpText>Information about Speaker</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <description>Enter Details of Speaker</description>
    <label>Speaker</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/EventTriggerHandler.cls
public class EventTriggerHandler {
    public static void inserting(List<Event_Speaker__c> newSpeakers) {
        Set<Id> speakerIds = new Set<Id>();
        Set<Id> eventIds = new Set<Id>();
        
        for (Event_Speaker__c newSpeaker : newSpeakers) {
            speakerIds.add(newSpeaker.Speaker__c);
            eventIds.add(newSpeaker.Event__c);
        }
        
        List<Event_Speaker__c> existingSpeakers = [SELECT Event__c, Speaker__c 
                                                   FROM Event_Speaker__c 
                                                   WHERE Speaker__c IN :speakerIds];

        Map<String, Id> existingSpeakerMap = new Map<String, Id>();
        for (Event_Speaker__c existingSpeaker : existingSpeakers) {
            String key = existingSpeaker.Speaker__c;
            existingSpeakerMap.put(key, existingSpeaker.Event__c);
        }
        
        for (Event_Speaker__c newSpeaker : newSpeakers) {
            String key = newSpeaker.Speaker__c;
            if (existingSpeakerMap.containsKey(key)) {
                newSpeaker.addError('Speaker already exists for this event.');
            }
        }
    }
    
    public static void updating(List<Event_Speaker__c> newSpeakers) {
        
        Set<Id> speakerIds = new Set<Id>();
        Set<Id> eventIds = new Set<Id>();
        
        for (Event_Speaker__c newSpeaker : newSpeakers) {
            speakerIds.add(newSpeaker.Speaker__c);
            eventIds.add(newSpeaker.Event__c);
        }
        
        List<Event_Speaker__c> existingSpeakers = [SELECT Event__c, Speaker__c 
                                                   FROM Event_Speaker__c 
                                                   WHERE Speaker__c IN :speakerIds];

        Map<String, Id> existingSpeakerMap = new Map<String, Id>();
        for (Event_Speaker__c existingSpeaker : existingSpeakers) {
            String key = existingSpeaker.Speaker__c;
            existingSpeakerMap.put(key, existingSpeaker.Event__c);
        }
        
        for (Event_Speaker__c newSpeaker : newSpeakers) {
            String key = newSpeaker.Speaker__c;
            if (existingSpeakerMap.containsKey(key)) {
                newSpeaker.addError('Speaker already exists for this event.');
            }
        }
    }
}