force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Enter Informations about Event</description>
    <label>Event</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <description>Enter Details of Event Speaker</description>
    <label>Event-Speaker</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Select Event</description>
    <inlineHelpText>Information of Event</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>Select Speaker</description>
    <inlineHelpText>Information about Speaker</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <description>Enter Details of Speaker</description>
    <label>Speaker</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/EventTriggerHandellerBrute.cls
public class EventTriggerHandellerBrute {
    public static void inserting(List<Event_Speaker__c> l1)
    {
        for(Event_Speaker__c it:l1)
        {
            List<Event_Speaker__c> var=[SELECT Event__c from Event_Speaker__c where Speaker__c =: it.Speaker__c];
            if(var.size()!=0)
            {
                it.addError('Speaker Already Exist');
            }
            else{
                Event_Speaker__c newone =new Event_Speaker__c();
                newone.Event__c=it.Event__c;
                newone.Speaker__c=it.Speaker__c;
                insert newone;
            }
        }
    }
    
    public static void updating(List<Event_Speaker__c> l1)
    {
        for(Event_Speaker__c it:l1)
        {
            List<Event_Speaker__c> var=[SELECT Event__c from Event_Speaker__c where Speaker__c =: it.Speaker__c];
            if(var.size()!=0)
            {
                it.addError('Speaker Already Exist');
            }
            else{
                Event_Speaker__c newone =[SELECT Id from Event_Speaker__c where Id =: it.Id];
                newone.Event__c=it.Event__c;
                newone.Speaker__c=it.Speaker__c;
                update newone;
            }
        }
    }
}