force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Enter Informations about Event</description>
    <label>Event</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>Enter End Date/Time</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter End Date/Time</inlineHelpText>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enter Event is live or not</description>
    <inlineHelpText>Gives Information about Event is live or not</inlineHelpText>
    <label>Live</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Enter your location</description>
    <inlineHelpText>Provides Information about Location</inlineHelpText>
    <label>Location</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>Enter Maximum Seats in your Event</description>
    <inlineHelpText>Maximum Seats in Event</inlineHelpText>
    <label>Max Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Select your Event Organizer</description>
    <inlineHelpText>Select your Event Organizer</inlineHelpText>
    <label>Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Enter Start Date-Time</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter Start Date-Time</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <description>Enter the Informations about Event Organizer for event</description>
    <label>Event Organizer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <description>Enter Details of Event Speaker</description>
    <label>Event-Speaker</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Select Event</description>
    <inlineHelpText>Information of Event</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>Select Speaker</description>
    <inlineHelpText>Information about Speaker</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Work Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work_Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location (Address Book)</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Street</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (Address Book)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <description>Enter Details of Speaker</description>
    <label>Speaker</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/EventTriggerHandlerTest.cls
@isTest
private class EventTriggerHandlerTest {
    
    @TestSetup static void insertTestRecords(){
        Location_Address_Book__c location = new Location_Address_Book__c();
        location.Name = 'Test Location';
        insert location;
        
        Event_Organizer__c organizer = new Event_Organizer__c();
        organizer.Name = 'Test Organizer';
        insert organizer;
        
        List<Event__c> eventsToInsert = TestUtility.createEventRecord('Test', 2);
        for(Event__c event : eventsToInsert){
        event.Organizer__c = organizer.Id;
        event.Location__c = location.Id;
        event.Start__c = Datetime.now();
        event.End__c = Datetime.now().addDays(10);
        event.Live__c = true;
        event.Max_Seats__c = 20;
        }
        insert eventsToInsert;
        
        
        Speaker__c speaker = new Speaker__c();
        speaker.Name = 'Test Speaker';
        insert speaker;
        
        Event_Speaker__c eventSpeaker1 = new Event_Speaker__c(Name='Aman Tyagi',Event__c = eventsToInsert[0].Id, Speaker__c = speaker.Id);
        insert eventSpeaker1;
        
        Event_Speaker__c eventSpeaker2 = new Event_Speaker__c(Name='Aman Rawli',Event__c = eventsToInsert[1].Id, Speaker__c = speaker.Id);

        Test.startTest();
        try {
            insert eventSpeaker2;
            System.assert(false, 'Duplicate booking should not be allowed.');
        } catch (DmlException e) {
            System.debug('Nothing');
        }
        Test.stopTest();
        
        
   }
   
    @isTest static void testDuplicateBooking(){
        List<Event_Speaker__c> testList = [SELECT Name,Speaker__c,Event__c FROM Event_Speaker__c];
        Test.startTest();
        try {
            insert testList;
            System.assert(false, 'Duplicate booking should not be allowed.');
        } catch (DmlException e) {
            List<Event_Speaker__c> testList2 = [SELECT Name,Speaker__c,Event__c FROM Event_Speaker__c];
            System.assertEquals(1,testList2.size());
        }
        Test.stopTest();
        System.assertEquals(1,testList.size());
        
    }
}