force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Enter Informations about Event</description>
    <label>Event</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>Enter End Date/Time</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter End Date/Time</inlineHelpText>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enter Event is live or not</description>
    <inlineHelpText>Gives Information about Event is live or not</inlineHelpText>
    <label>Live</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EventApexBatch.cls
public class EventApexBatch implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext bc)
    {
        return Database.getQueryLocator([SELECT Id FROM Event__c WHERE End__c < :System.today().addMonths(-2) AND Live__c = false]);
    }
    
    public void execute(Database.BatchableContext bc, List<Event__c> event)
    {
        delete event;
    }
    
    public void finish(Database.BatchableContext bc) {
        try {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(new String[] {'aman.tyagi@mirketa.com'});
            mail.setSubject('Batch Execution Complete');
            mail.setPlainTextBody('The execution of the OldEventsBatch has been processed.');

            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
            
            System.debug('Batch execution complete and email sent to admin.');
        } catch (Exception e) {
            System.debug('Error sending email: ' + e.getMessage());
        }
    }
}