force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Enter Informations about Event</description>
    <label>Event</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>Enter End Date/Time</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter End Date/Time</inlineHelpText>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enter Event is live or not</description>
    <inlineHelpText>Gives Information about Event is live or not</inlineHelpText>
    <label>Live</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Enter your name</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter your name</inlineHelpText>
    <label>Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Enter Start Date-Time</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter Start Date-Time</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/EventApexBatchTest.cls
@isTest
public class EventApexBatchTest {
    @isTest
    public static void testBatchClass()
    {
        List<Event__c> list1=new List<Event__c>();
        for(Integer i=0;i<100;i++)
        {
            list1.add(new Event__c(Name__c='Farewell Party'+i, Start__c=Date.today(), End__c=Date.today().addDays(10),Live__c=true));
        }
        for(Integer i=0;i<100;i++)
        {
            list1.add(new Event__c(Name__c='Farewell Party'+i, Start__c=Date.today().addMonths(-4), End__c=Date.today().addMonths(-3),Live__c=false));
        }
        
        insert list1;
        Test.startTest();
        EventApexBatch event=new EventApexBatch();
        Id batchId=Database.executeBatch(event,200);
        Test.stopTest();
        List<Event__c> updated=[Select Id from Event__c where Live__c=false];
        System.assertEquals(0,updated.size());
        
        
    }
}